/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_shop;

import javax.swing.*;

/**
 *
 * @author Abrar Faiyaz Khan
 */
public class shopOwner extends javax.swing.JFrame {

    /**
     * Creates new form shopOwner
     */
    public shopOwner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton9 = new javax.swing.JButton();
        panel_owner = new javax.swing.JPanel();
        label_head = new javax.swing.JLabel();
        owner_usename = new javax.swing.JLabel();
        payRent = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ownerLogout = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        owner_rent = new javax.swing.JLabel();
        owner_dueRent = new javax.swing.JLabel();
        placeComplaint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        owner_shopName = new javax.swing.JLabel();
        notif = new javax.swing.JButton();

        jButton9.setText("jButton9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_owner.setBackground(new java.awt.Color(50, 196, 210));
        panel_owner.setPreferredSize(new java.awt.Dimension(1000, 562));

        label_head.setFont(new java.awt.Font("Sylfaen", 1, 40)); // NOI18N
        label_head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_head.setText("Shop Owner");

        owner_usename.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        owner_usename.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        owner_usename.setText("owner11");
        owner_usename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                changeName(evt);
            }
        });

        payRent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        payRent.setText("Pay Rent");
        payRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payRentActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Place Complaint");

        ownerLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ownerLogout.setText("Log Out");
        ownerLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerLogoutActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Leave Shop");

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("Due Rent               :");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_shop/logo.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setText("Rent                      :");

        owner_rent.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        owner_rent.setText("30000");

        owner_dueRent.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        owner_dueRent.setText("60000");

        placeComplaint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeComplaint.setText("Place Complaint");
        placeComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeComplaintActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel2.setText("Shop Name             :");

        owner_shopName.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        owner_shopName.setText("shop11");

        notif.setBackground(new java.awt.Color(50, 196, 210));
        notif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_shop/notification.png"))); // NOI18N
        notif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ownerLayout = new javax.swing.GroupLayout(panel_owner);
        panel_owner.setLayout(panel_ownerLayout);
        panel_ownerLayout.setHorizontalGroup(
            panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ownerLayout.createSequentialGroup()
                .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(147, 147, 147)
                        .addComponent(label_head, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(notif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(owner_usename, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownerLogout))))
                .addGap(22, 22, 22))
            .addGroup(panel_ownerLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(owner_rent, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(owner_dueRent, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(owner_shopName)))
                .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(payRent, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(placeComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_ownerLayout.setVerticalGroup(
            panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ownerLayout.createSequentialGroup()
                .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(label_head, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(owner_usename, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ownerLogout))
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(notif, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(owner_shopName))
                .addGap(37, 37, 37)
                .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(owner_rent))
                .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ownerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(panel_ownerLayout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panel_ownerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panel_ownerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(owner_dueRent)
                            .addComponent(payRent, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(placeComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ownerLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerLogoutActionPerformed
        // TODO add your handling code here:
        loginPage login = new loginPage();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_ownerLogoutActionPerformed

    private void changeName(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_changeName
        // TODO add your handling code here:
    }//GEN-LAST:event_changeName

    private void payRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payRentActionPerformed
        // TODO add your handling code here:
        PayRent pay = new PayRent();
        pay.setVisible(true);
//        pay.setResizable(false);
//        pay.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
//        pay.dispose();
    }//GEN-LAST:event_payRentActionPerformed

    private void placeComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeComplaintActionPerformed
        // TODO add your handling code here:
        Complain comp = new Complain();
        comp.setVisible(true);
    }//GEN-LAST:event_placeComplaintActionPerformed

    private void notifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifActionPerformed
        // TODO add your handling code here:
        shopOwner_notif notif = new shopOwner_notif();
        notif.setVisible(true);
    }//GEN-LAST:event_notifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shopOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shopOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shopOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shopOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shopOwner().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_head;
    private javax.swing.JButton notif;
    private javax.swing.JButton ownerLogout;
    private javax.swing.JLabel owner_dueRent;
    private javax.swing.JLabel owner_rent;
    private javax.swing.JLabel owner_shopName;
    private javax.swing.JLabel owner_usename;
    private javax.swing.JPanel panel_owner;
    private javax.swing.JButton payRent;
    private javax.swing.JButton placeComplaint;
    // End of variables declaration//GEN-END:variables
}
